export const attorneys = [
  {
    name: "Mugabe Oscar",
    slug: "mugabe-oscar",
    position: "Managing Partner",
    bio: "Mugabe Oscar is a Holder Bachelor of Laws Degree (Honours) from Makerere University and a Post Graduate Diploma in Legal Practice from Law Development Centre He is an expert in offering practical legal solutions to private sector service led environments working with and managing people and has been a key resource in managing complex legal cases from the beginning to end. Mr. Mugabe has extensive experience as company Secretary of Multi National corporations and has overseen road construction projects such as the Kampala-Entebbe Express Highway and the Expansion of the Entebbe International Airport.",
    image: "../assets/oscar.jpg",
    alt: "Mugabe Oscar",
    email: "oscarm@apricusadvocates.com",
    practiceAreas: [
      "Construction and Engineering law",
      "Conveyancing and Real Estate",
      "Corporate and Commercial Transaction",
      "Land transactions and Property Management",
      "Corporate Governance",
      "Civil and Criminal litigation",
    ],
  },
  {
    name: "Anita Nantale",
    slug: "anita-nantale",
    position: "Partner",
    bio: "Anita graduated with a Bachelor of Laws degree and attained a Post Graduate Diploma in Legal Practice from the Law Development Centre. Anita started her legal practice at the Uganda National Roads Authority after her internship with the Attorney General’s Chambers providing both legal advisory and drafting pleadings. She is highly experienced in legal private practice.",
    image: "../assets/anita.jpeg",
    alt: "Anita Nantale",
    email: "anitan@apricusadvocates.com",
    practiceAreas: ["Immigration and Refugee law", "Banking Securities", "Procurement Law", "Probate succession and Trusts", "Real Estate and Property management"],
  },
  {
    name: "Ezra Mugabi",
    slug: "ezra-mugabi",
    position: "Partner",
    bio: "Ezra graduated with a Bachelor of Laws degree, attained the Post Graduate Diploma in Legal Practice of the Law Development Centre. Ezra is a seasoned Legal Practioner and has provided legal consultancy to Multi-Million dollar projects especially in areas of Oil and Energy.F ",
    image: "../assets/ezra.jpg",
    alt: "Ezra Mugabi",
    email: "ezram@apricusadvocates.com",
    practiceAreas: ["Oil and Gas Law", " Corporate and Commercial Transactions", "Real Estate and Property Management", "Taxation Law", "  Insurance Law"],
  },
  {
    name: "Kamugisha Blaise",
    slug: "blaise",
    position: "CEO",
    bio: "Blaise is a holder of Bachelors of Law degree from Makerere University and has pursued a post graduate diploma in legal practice from Law Delopment Center.He is currently the Chief Executive Officer handling all the day to day affairs of the firm. His experience spans across public - private partnerships, mergers and acquisitions, corporate advisory department, energy, banking and finance. Blaise is currently pursuing an LLM from the University of East London,UK.",
    image: "../assets/blaise.jpeg",
    alt: "Kamugisha Blaise",
    email: "blaisek@apricusadvocates.com",
    practiceAreas: ["Land and Property transactions", "Public Private Parternerships", "Civil and Criminal Litigation", "Insurance law", "Taxation law"],
  },
  {
    name: "Anyine Mercy",
    slug: "anyine-mercy",
    position: "Associate",

    image: "../assets/mercy.jpeg",
    alt: "Anyine Mercy",
    professionallQualifications: ["LLB (Hons.), Dar es Salaam", "     Diploma in Legal Practice, Law Development Centre"],
  },
  {
    name: "Amusugut Grace Ruth",
    slug: "grace-ruth",
    position: "Associate",
    image: "../assets/grace.jpeg",
    alt: "Amusugut Grace Ruth",
    professionallQualifications: [" LLB (Hons.), Uganda Christian University (Mukono)", " Diploma in Legal Practice, Law Development Centre"],
  },
];
